### AI_multimodal_data_parsing

In [2]:
import json
import numpy as np
import pandas as pd

with open("C:/Users/user/OneDrive/Desktop/연구실/2019-01-005.멀티모달영상_sample (1)/라벨데이터/clip_13.json","r",encoding='UTF8') as clip13_json:
    clip_13 = json.load(clip13_json)

with open("C:/Users/user/OneDrive/Desktop/연구실/2019-01-005.멀티모달영상_sample (1)/라벨데이터/clip_30.json","r",encoding='UTF8') as clip30_json:
    clip_30 =json.load(clip30_json)

In [3]:
clip_13

{'clip_id': '13',
 'nr_frame': '1680',
 'situation': '어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.',
 'data': {'1143': {'2': {'frame': '1143',
    'predicate': {'2': 'sit'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 4.0, 'emotion': 'surprise', 'arousal': 6.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '1'}},
    'xtl': '481.90',
    'label': '사람',
    'ybr': '1059.60',
    'position': {'1': 'ahead_behind'},
    'ytl': '129.80',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 980,
     'script_end': 1195,
     'script': '아니? 이거는 간식이야. 다이어트는 조금씩 자주 먹는게 좋다고 하더라고. 이거 먹고 토마토 한 박스 먹으려고.',
     'intent': '응대/답변',
     'morpheme': [['알', 'VV'],
      ['니', 'ECD'],
      ['?', 'SF'],
      ['이거', 'NP'],
      ['는', 'JX'],
      ['간식', 'NNG'],
      ['이', 'VCP'],
      ['야', 'EFN'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['는', 'JX'],
      ['조금씩', 'MAG'],
      ['자주', 'MAG'],
      ['먹', 'VV'],
      ['는', 'ETD'],
      ['것', 'NNB'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다고', 'EFN'],
      ['하', 'VV'],
      ['더', 'EPT'],
      ['라고', 'EFN'],
      ['.', 'SF'],
      ['이거', 'NP'],
      ['먹', 'VV'],
      ['고', 'ECE'],
      ['토마토', 'NNG'],
      ['한', 'MDN'],
      ['박스', 'NNG'],
      ['먹', 'VV'],
      ['으려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '912.70',
    'person_id': '2'},
   '3': {'frame': '1143',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '1143',
    'predicate': {'1': 'eat_drink'},
    'emotion': {'image': {'valence': 8.0, 'emotion': 'happy', 'arousal': 4.0},
     'sound': {'valence': 4.0, 'emotion': 'surprise', 'arousal': 6.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '1'}},
    'xtl': '815.93',
    'label': '사람',
    'ybr': '965.10',
    'position': {'2': 'ahead_behind'},
    'ytl': '130.04',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 980,
     'script_end': 1195,
     'script': '아니? 이거는 간식이야. 다이어트는 조금씩 자주 먹는게 좋다고 하더라고. 이거 먹고 토마토 한 박스 먹으려고.',
     'intent': '응대/답변',
     'morpheme': [['알', 'VV'],
      ['니', 'ECD'],
      ['?', 'SF'],
      ['이거', 'NP'],
      ['는', 'JX'],
      ['간식', 'NNG'],
      ['이', 'VCP'],
      ['야', 'EFN'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['는', 'JX'],
      ['조금씩', 'MAG'],
      ['자주', 'MAG'],
      ['먹', 'VV'],
      ['는', 'ETD'],
      ['것', 'NNB'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다고', 'EFN'],
      ['하', 'VV'],
      ['더', 'EPT'],
      ['라고', 'EFN'],
      ['.', 'SF'],
      ['이거', 'NP'],
      ['먹', 'VV'],
      ['고', 'ECE'],
      ['토마토', 'NNG'],
      ['한', 'MDN'],
      ['박스', 'NNG'],
      ['먹', 'VV'],
      ['으려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '1368.53',
    'person_id': '2'},
   '4': {'frame': '1143',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.50',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '847.90'}},
  '241': {'2': {'frame': '241',
    'predicate': {'2': 'sit', '4': 'eat_drink'},
    'label': '사람',
    'xtl': '464.95',
    'position': {'1': 'ahead_behind'},
    'ytl': '106.31',
    'ybr': '1002.40',
    'xbr': '923.56',
    'person_id': '2'},
   '3': {'frame': '241',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '241',
    'predicate': {'1': 'catch'},
    'label': '사람',
    'xtl': '831.86',
    'position': {'2': 'ahead_behind'},
    'ytl': '131.18',
    'ybr': '962.81',
    'xbr': '1389.24',
    'person_id': '2'},
   '4': {'frame': '241',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '224.21',
    'ybr': '312.10',
    'xbr': '793.12',
    'xtl': '708.09'}},
  '1535': {'2': {'frame': '1535',
    'predicate': {'2': 'sit'},
    'label': '사람',
    'xtl': '480.30',
    'position': {'1': 'ahead_behind'},
    'ytl': '121.40',
    'ybr': '1059.60',
    'xbr': '911.10',
    'person_id': '2'},
   '3': {'frame': '1535',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '1535',
    'predicate': {'1': 'eat_drink'},
    'label': '사람',
    'xtl': '818.42',
    'position': {'2': 'ahead_behind'},
    'ytl': '129.20',
    'ybr': '965.10',
    'xbr': '1371.02',
    'person_id': '2'},
   '4': {'frame': '1535',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.50',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '847.90'}},
  '566': {'2': {'frame': '566',
    'predicate': {'2': 'sit'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 6.0, 'emotion': 'angry', 'arousal': 4.0},
     'multimodal': {'valence': 4.0, 'emotion': 'contempt', 'arousal': 6.0},
     'text': {'valence': '3', 'emotion': 'neutral', 'arousal': '4'}},
    'xtl': '463.84',
    'label': '사람',
    'ybr': '1002.40',
    'position': {'1': 'ahead_behind'},
    'ytl': '119.90',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 550,
     'script_end': 634,
     'script': '저번에는 저번이고, 오늘은 오늘이지.',
     'intent': '진술/주장',
     'morpheme': [['저번', 'NNG'],
      ['에', 'JKM'],
      ['는', 'JX'],
      ['저번', 'NNG'],
      ['이', 'VCP'],
      ['고', 'ECE'],
      [',', 'SP'],
      ['오늘', 'NNG'],
      ['은', 'JX'],
      ['오늘', 'NNG'],
      ['이', 'VCP'],
      ['지', 'EFN'],
      ['.', 'SF']]},
    'xbr': '929.70',
    'person_id': '2'},
   '3': {'frame': '566',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '566',
    'predicate': {'1': 'eat_drink'},
    'emotion': {'image': {'valence': 9.0, 'emotion': 'happy', 'arousal': 5.0},
     'sound': {'valence': 6.0, 'emotion': 'angry', 'arousal': 4.0},
     'multimodal': {'valence': 4.0, 'emotion': 'contempt', 'arousal': 6.0},
     'text': {'valence': '3', 'emotion': 'neutral', 'arousal': '4'}},
    'xtl': '819.52',
    'label': '사람',
    'ybr': '959.06',
    'position': {'2': 'ahead_behind'},
    'ytl': '129.24',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 550,
     'script_end': 634,
     'script': '저번에는 저번이고, 오늘은 오늘이지.',
     'intent': '진술/주장',
     'morpheme': [['저번', 'NNG'],
      ['에', 'JKM'],
      ['는', 'JX'],
      ['저번', 'NNG'],
      ['이', 'VCP'],
      ['고', 'ECE'],
      [',', 'SP'],
      ['오늘', 'NNG'],
      ['은', 'JX'],
      ['오늘', 'NNG'],
      ['이', 'VCP'],
      ['지', 'EFN'],
      ['.', 'SF']]},
    'xbr': '1384.24',
    'person_id': '2'},
   '4': {'frame': '566',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.50',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '847.90'}},
  '395': {'2': {'frame': '395',
    'predicate': {'2': 'sit', '4': 'catch'},
    'label': '사람',
    'xtl': '465.96',
    'position': {'1': 'ahead_behind'},
    'ytl': '106.31',
    'ybr': '1002.40',
    'xbr': '934.27',
    'person_id': '2'},
   '3': {'frame': '395',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '395',
    'predicate': {'1': 'eat_drink'},
    'label': '사람',
    'xtl': '827.54',
    'position': {'2': 'ahead_behind'},
    'ytl': '132.43',
    'ybr': '966.11',
    'xbr': '1383.16',
    'person_id': '2'},
   '4': {'frame': '395',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '393.80',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '842.03'}},
  '1082': {'2': {'frame': '1082',
    'predicate': {'2': 'sit'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 4.0, 'emotion': 'surprise', 'arousal': 6.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '1'}},
    'xtl': '474.98',
    'label': '사람',
    'ybr': '1059.55',
    'position': {'1': 'ahead_behind'},
    'ytl': '126.07',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 980,
     'script_end': 1195,
     'script': '아니? 이거는 간식이야. 다이어트는 조금씩 자주 먹는게 좋다고 하더라고. 이거 먹고 토마토 한 박스 먹으려고.',
     'intent': '응대/답변',
     'morpheme': [['알', 'VV'],
      ['니', 'ECD'],
      ['?', 'SF'],
      ['이거', 'NP'],
      ['는', 'JX'],
      ['간식', 'NNG'],
      ['이', 'VCP'],
      ['야', 'EFN'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['는', 'JX'],
      ['조금씩', 'MAG'],
      ['자주', 'MAG'],
      ['먹', 'VV'],
      ['는', 'ETD'],
      ['것', 'NNB'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다고', 'EFN'],
      ['하', 'VV'],
      ['더', 'EPT'],
      ['라고', 'EFN'],
      ['.', 'SF'],
      ['이거', 'NP'],
      ['먹', 'VV'],
      ['고', 'ECE'],
      ['토마토', 'NNG'],
      ['한', 'MDN'],
      ['박스', 'NNG'],
      ['먹', 'VV'],
      ['으려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '912.70',
    'person_id': '2'},
   '3': {'frame': '1082',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '1082',
    'predicate': {'1': 'eat_drink'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 4.0, 'emotion': 'surprise', 'arousal': 6.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '1'}},
    'xtl': '818.61',
    'label': '사람',
    'ybr': '965.10',
    'position': {'2': 'ahead_behind'},
    'ytl': '130.47',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 980,
     'script_end': 1195,
     'script': '아니? 이거는 간식이야. 다이어트는 조금씩 자주 먹는게 좋다고 하더라고. 이거 먹고 토마토 한 박스 먹으려고.',
     'intent': '응대/답변',
     'morpheme': [['알', 'VV'],
      ['니', 'ECD'],
      ['?', 'SF'],
      ['이거', 'NP'],
      ['는', 'JX'],
      ['간식', 'NNG'],
      ['이', 'VCP'],
      ['야', 'EFN'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['는', 'JX'],
      ['조금씩', 'MAG'],
      ['자주', 'MAG'],
      ['먹', 'VV'],
      ['는', 'ETD'],
      ['것', 'NNB'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다고', 'EFN'],
      ['하', 'VV'],
      ['더', 'EPT'],
      ['라고', 'EFN'],
      ['.', 'SF'],
      ['이거', 'NP'],
      ['먹', 'VV'],
      ['고', 'ECE'],
      ['토마토', 'NNG'],
      ['한', 'MDN'],
      ['박스', 'NNG'],
      ['먹', 'VV'],
      ['으려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '1371.21',
    'person_id': '2'},
   '4': {'frame': '1082',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.50',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '847.90'}},
  '140': {'2': {'frame': '140',
    'predicate': {'2': 'sit'},
    'label': '사람',
    'xtl': '462.53',
    'position': {'1': 'ahead_behind'},
    'ytl': '106.31',
    'ybr': '1002.40',
    'xbr': '915.22',
    'person_id': '2'},
   '3': {'frame': '140',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '140',
    'predicate': {'1': 'catch'},
    'label': '사람',
    'xtl': '836.71',
    'position': {'2': 'ahead_behind'},
    'ytl': '129.25',
    'ybr': '959.54',
    'xbr': '1390.62',
    'person_id': '2'},
   '4': {'frame': '140',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '397.51',
    'ybr': '472.81',
    'xbr': '904.29',
    'xtl': '844.05'}},
  '805': {'2': {'frame': '805',
    'predicate': {'2': 'sit'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 6.0, 'emotion': 'happy', 'arousal': 2.0},
     'multimodal': {'valence': 6.0, 'emotion': 'happy', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '2'}},
    'xtl': '463.84',
    'label': '사람',
    'ybr': '1004.56',
    'position': {'1': 'ahead_behind'},
    'ytl': '119.90',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 770,
     'script_end': 860,
     'script': '초콜릿 바. 다이어트에 초콜릿이 좋다 그래서.',
     'intent': '응대/답변',
     'morpheme': [['초콜릿', 'NNG'],
      ['바', 'NNG'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['에', 'JKM'],
      ['초콜릿', 'NNG'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다', 'ECS'],
      ['그리하', 'VV'],
      ['여서', 'ECD'],
      ['.', 'SF']]},
    'xbr': '912.70',
    'person_id': '2'},
   '3': {'frame': '805',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '805',
    'predicate': {'1': 'eat_drink'},
    'emotion': {'image': {'valence': 9.0, 'emotion': 'happy', 'arousal': 4.0},
     'sound': {'valence': 6.0, 'emotion': 'happy', 'arousal': 2.0},
     'multimodal': {'valence': 6.0, 'emotion': 'happy', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '2'}},
    'xtl': '823.45',
    'label': '사람',
    'ybr': '963.59',
    'position': {'2': 'ahead_behind'},
    'ytl': '126.24',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 770,
     'script_end': 860,
     'script': '초콜릿 바. 다이어트에 초콜릿이 좋다 그래서.',
     'intent': '응대/답변',
     'morpheme': [['초콜릿', 'NNG'],
      ['바', 'NNG'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['에', 'JKM'],
      ['초콜릿', 'NNG'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다', 'ECS'],
      ['그리하', 'VV'],
      ['여서', 'ECD'],
      ['.', 'SF']]},
    'xbr': '1372.32',
    'person_id': '2'},
   '4': {'frame': '805',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.50',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '847.90'}},
  '414': {'2': {'frame': '414',
    'predicate': {'2': 'sit', '4': 'catch'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 5.0, 'emotion': 'happy', 'arousal': 1.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 5.0},
     'text': {'valence': '3', 'emotion': 'sad', 'arousal': '2'}},
    'xtl': '464.81',
    'label': '사람',
    'ybr': '1002.40',
    'position': {'1': 'ahead_behind'},
    'ytl': '106.31',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 410,
     'script_end': 464,
     'script': '나 다이어트 하려고.',
     'intent': '진술/주장',
     'morpheme': [['나', 'VV'],
      ['아', 'ECS'],
      ['다이어트', 'NNG'],
      ['하', 'VV'],
      ['려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '935.59',
    'person_id': '2'},
   '3': {'frame': '414',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '414',
    'predicate': {'1': 'eat_drink'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 5.0, 'emotion': 'happy', 'arousal': 1.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 5.0},
     'text': {'valence': '3', 'emotion': 'sad', 'arousal': '2'}},
    'xtl': '825.50',
    'label': '사람',
    'ybr': '965.45',
    'position': {'2': 'ahead_behind'},
    'ytl': '131.52',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 410,
     'script_end': 464,
     'script': '나 다이어트 하려고.',
     'intent': '진술/주장',
     'morpheme': [['나', 'VV'],
      ['아', 'ECS'],
      ['다이어트', 'NNG'],
      ['하', 'VV'],
      ['려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '1385.59',
    'person_id': '2'},
   '4': {'frame': '414',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '396.35',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '845.22'}},
  '389': {'2': {'frame': '389',
    'predicate': {'2': 'sit', '4': 'catch'},
    'label': '사람',
    'xtl': '466.32',
    'position': {'1': 'ahead_behind'},
    'ytl': '106.31',
    'ybr': '1002.40',
    'xbr': '933.85',
    'person_id': '2'},
   '3': {'frame': '389',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '389',
    'predicate': {'1': 'eat_drink'},
    'label': '사람',
    'xtl': '828.18',
    'position': {'2': 'ahead_behind'},
    'ytl': '132.72',
    'ybr': '966.32',
    'xbr': '1382.39',
    'person_id': '2'},
   '4': {'frame': '389',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '392.99',
    'ybr': '475.25',
    'xbr': '912.55',
    'xtl': '841.02'}},
  '181': {'2': {'frame': '181',
    'predicate': {'2': 'sit', '4': 'catch'},
    'label': '사람',
    'xtl': '475.82',
    'position': {'1': 'ahead_behind'},
    'ytl': '106.31',
    'ybr': '1002.40',
    'xbr': '919.38',
    'person_id': '2'},
   '3': {'frame': '181',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '181',
    'predicate': {'1': 'catch'},
    'label': '사람',
    'xtl': '834.74',
    'position': {'2': 'ahead_behind'},
    'ytl': '131.87',
    'ybr': '962.70',
    'xbr': '1390.06',
    'person_id': '2'},
   '4': {'frame': '181',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '394.60',
    'ybr': '469.90',
    'xbr': '899.81',
    'xtl': '839.57'}},
  '1124': {'2': {'frame': '1124',
    'predicate': {'2': 'sit'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 4.0, 'emotion': 'surprise', 'arousal': 6.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '1'}},
    'xtl': '481.90',
    'label': '사람',
    'ybr': '1059.60',
    'position': {'1': 'ahead_behind'},
    'ytl': '131.53',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 980,
     'script_end': 1195,
     'script': '아니? 이거는 간식이야. 다이어트는 조금씩 자주 먹는게 좋다고 하더라고. 이거 먹고 토마토 한 박스 먹으려고.',
     'intent': '응대/답변',
     'morpheme': [['알', 'VV'],
      ['니', 'ECD'],
      ['?', 'SF'],
      ['이거', 'NP'],
      ['는', 'JX'],
      ['간식', 'NNG'],
      ['이', 'VCP'],
      ['야', 'EFN'],
      ['.', 'SF'],
      ['다이어트', 'NNG'],
      ['는', 'JX'],
      ['조금씩', 'MAG'],
      ['자주', 'MAG'],
      ['먹', 'VV'],
      ['는', 'ETD'],
      ['것', 'NNB'],
      ['이', 'JKS'],
      ['좋', 'VA'],
      ['다고', 'EFN'],
      ['하', 'VV'],
      ['더', 'EPT'],
      ['라고', 'EFN'],
      ['.', 'SF'],
      ['이거', 'NP'],
      ['먹', 'VV'],
      ['고', 'ECE'],
      ['토마토', 'NNG'],
      ['한', 'MDN'],
      ['박스', 'NNG'],
      ['먹', 'VV'],
      ['으려고', 'ECD'],
      ['.', 'SF']]},
    'xbr': '912.70',
    'person_id': '2'},
   '3': {'frame': '1124',
    'predicate': {},
    'label': '물잔',
    'position': {},
    'ytl': '398.48',
    'ybr': '464.75',
    'xbr': '1031.61',
    'xtl': '963.84'},
   '1': {'frame': '1124',
    'predicate': {'1': 'eat_drink'},
    'emotion': {'image': {'valence': 5.0,
      'emotion': 'neutral',
      'arousal': 5.0},
     'sound': {'valence': 4.0, 'emotion': 'surprise', 'arousal': 6.0},
     'multimodal': {'valence': 6.0, 'emotion': 'neutral', 'arousal': 6.0},
     'text': {'valence': '5', 'emotion': 'neutral', 'arousal': '1'}},
    'xtl': '816.93',
    'label': '사람',
    'ybr': '965.10',
    'position': {'2': 'ahead_behind'},
    'ytl': '130.17',
    'text': {'strategy': '자기대화 (SD)',
     'script_start': 980,
     'script_end': 1195,
     'script': '아니? 이거는 간식이야. 다이어트는 조금씩 자주 먹는게 좋다고 하더라고. 이거 먹고 토마토 한 박스 먹으려고.',
     'intent': '응대/답변',
     'morpheme': [['알', 'VV'],
      ['니', 'ECD'],
      ['?', 'SF'],
      ['이거', 'NP'],
      ['는', 'JX'],
      ['간식', 'NNG'],

In [4]:
clip13DF1 = pd.DataFrame(data = [list(clip_13.values())],columns = list(clip_13.keys()))

clip13DF1.head(5)

,clip_id,nr_frame,situation,data,video_size,actor
0,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'1143': {'2': {'frame': '1143', 'predicate': ...","{'width': '1920', 'height': '1080'}","{'2': {'age': 27, 'gender': '여성'}, '1': {'age'..."

### 메타 데이터 정보를 분석하면 다음과 같습니다.

- clip_id : 영상 클립 ID
- nr_frame : 영상 전체 프레임 수
- situation : 상황 정보 
- data : 프레임 데이터(여기에서 여러 분화로 갈립니다)
- video_size : 영상 해상도
- actor : 등장 인물 정보

#### 'data'가 다시 또 세분화되는데, 살펴보겠습니다.

- nr_frame을 다시 제시해줍니다. 이 안에 또 엄청 복잡하게 nested 되어 있습니다.
- "2","1"로 보이는 숫자 : 인물/객체 정보 ID를 말합니다.
 - frame : 프레임정보를 또 기재합니다.
  - predicate : 서술어를 말하는데, 아직 잘 와닿지 않습니다.
  - emotion : 감정 정보
  - image : 이미지 감정 정보
    - valence : 감정 긍부정도(float)
    - emotion : 작은 emotion : neutral 등등 구체적인 정보(object)
    - arousal : 감정 세기(float)
    - xxx : 부수 감정
  - label : 인물 / 객체 종류 (1143의 경우 1: 화내는 인간 2: 카페 알바 3: 텀블러)
  - position : 위치 관계 정보
    - 인물 정보 ID 에 대한 상대 위치 인물 ID : ahead_behind 처럼 인물 ID의 상대 위치 
  - xtl,ytl : 사각형의 왼쪽 위 꼭지점의 좌표
  - xbr,ybr : 사각형의 오른쪽 아래 꼭지점의 좌표
  - person_id : 인물 객체 정보 ID를 말합니다.


   - text : 발화분석 정보
     - strategy : 대화 전략
     - script_start : 발화 시작 시간(int)
     - script_end : 발화 종료 시간(int)
     - script : 발화 스크립트
     - intent : 발화 의도 
     - morpheme : 문장 품사

In [5]:
clip13DF2 = pd.DataFrame(clip_13)

clip13DF2.head(5)

,clip_id,nr_frame,situation,data,video_size,actor
1143,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'2': {'frame': '1143', 'predicate': {'2': 'si...",NaN,NaN
241,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'2': {'frame': '241', 'predicate': {'2': 'sit...",NaN,NaN
1535,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'2': {'frame': '1535', 'predicate': {'2': 'si...",NaN,NaN
566,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'2': {'frame': '566', 'predicate': {'2': 'sit...",NaN,NaN
395,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'2': {'frame': '395', 'predicate': {'2': 'sit...",NaN,NaN

### 0. 데이터 정제 방향

1) clip13, clip30 모두 공통적으로 clip_id / nr_frame / situation을 가지고 있으므로 이들을 제외하여 두 테이블로 만들어야 합니다.



2) clip13DF2 테이블에서 결측치로 확인되는 video_size와 actor를 해결하기 위해 clip13DF1에 주어진 video_size와 actor를 빼내어 따로 clip_13_video 와 clip13_actors를 만들어줍니다.



3) clip13DF2 테이블에서는 frame 별로 인물 정보가 예쁘게 매칭이 되어있음을 확인할 수 있습니다. clip13DF2[index,data]만을 빼내어 새 테이블을 만들 수 있습니다.



4) clip13DF2['data']에 상당히 깊은 깊이가 존재합니다. 이를 해결하기 위해 분화를 해줍니다. 이게 진짜 상당히 오래 걸릴 것 같습니다.

In [6]:
clip13DF0 = clip13DF2.drop(['data','video_size','actor'],axis=1,inplace=False)
#

#이렇게만 하면 너무 중복된 값이 많다.. 
clip13DF0 = clip13DF0.reset_index(inplace=False)

clip13DF0

       index clip_id nr_frame                       situation
0       1143      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
1        241      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
2       1535      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
3        566      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
4        395      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
...      ...     ...      ...                             ...
1574    1167      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
1575   width      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
1576  height      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
1577       2      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.
1578       1      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.

[1579 rows x 4 columns]

#### 1. get_meta_data : 메타 정보를 반환하는 함수입니다.

In [7]:
def get_meta_data(json):
    df2 = pd.DataFrame(json)
    
    df0 = df2.drop(['data','video_size','actor'],axis=1,inplace=False)
    
    df0=df0.reset_index(inplace=False)
    df0 = df0[df0.index.values==0]
    
    df0 = df0.drop(['index'],axis=1,inplace=False)
    
    return df0

#### 1-1) 테스트

In [8]:
tmpdf = get_meta_data(clip_13)
tmpdf

  clip_id nr_frame                       situation
0      13     1680  어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.

#### 2. get_actors : 배우 정보를 반환하는 함수입니다.

In [9]:
def get_actors(json):
    df1 = pd.DataFrame(data = [list(json.values())],columns = list(json.keys()))
    tmplist = list(df1['actor'][0].values())
    resdf = pd.DataFrame(tmplist)
    
    return resdf

#### 2-1) 테스트

In [10]:
restmp = get_actors(clip_13)
restmp

   age gender
0   27     여성
1   27     여성

#### 3. get_all_meta : 중복되는 모든 키 요소를 제외하여 메타 정보만 보여주는 함수입니다.
- 쉽게 말하면 data,actor를 제외한 결과를 보여주는 함수입니다.

In [11]:
clip13DF11 = pd.DataFrame(data = [list(clip_13.values())],columns = list(clip_13.keys()))
clip13DF11

,clip_id,nr_frame,situation,data,video_size,actor
0,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'1143': {'2': {'frame': '1143', 'predicate': ...","{'width': '1920', 'height': '1080'}","{'2': {'age': 27, 'gender': '여성'}, '1': {'age'..."

In [12]:
clip13DF11['video_size'][0].keys()

dict_keys(['width', 'height'])

In [13]:
clip13DF11['video_size'][0].values()

dict_values(['1920', '1080'])

In [14]:
def get_all_data(json):
    clip13DF11 = pd.DataFrame(data = [list(json.values())],columns = list(json.keys()))
    
    clip13DF11 = clip13DF11.drop(['data','actor'], axis=1, inplace=False)
    
    return clip13DF11

#### 3-1) 테스트

In [15]:
tmpdf = get_all_data(clip_13)
tmpdf

,clip_id,nr_frame,situation,video_size
0,13,1680,어릴 때부터 친구인 두 사람. 카페에서 대화를 나눈다.,"{'width': '1920', 'height': '1080'}"

### 3. clip13DF2 테이블에서는 frame 별로 인물 정보가 예쁘게 매칭이 되어있음을 확인할 수 있습니다. 
- clip13DF2[index,data]만을 빼내어 새 테이블을 만들 수 있습니다.
- 그 전에 clip13DF2['data']의 메타 정보를 분해하여 알아보겠습니다.

#### 3-1). data만 따로 떼고, 결측치를 제거합니다.

In [16]:
filteredDF2 = clip13DF2[['data']]

#filteredDF2

print('결측치 제거 전 전체 크기 : ',len(filteredDF2))
filteredDF2 = filteredDF2.dropna(axis=0)

print('결측치 제거 후 전체 크기 : ',len(filteredDF2))

결측치 제거 전 전체 크기 :  1579
결측치 제거 후 전체 크기 :  1575

#### 3-2) 상황 설명
- 전체 json을 DF로 바꾼 뒤 결측치 제거
- DF['data']가 복잡하니까 이것을 frame / frame 데이터로 나눈것임
- get_frame_info는 그 데이터의 frame 정보만을 담은 리스트임 str형이 들어가 있음
- get_frame_data는 그 데이터의 frame 데이터만을 담은 리스트임 dict형이 들어가 있음
- 모두 array가 아닌 list를 반환함
- 요구에 따라 array로 바꿔서 사용할 수 있음

In [17]:
def get_frame_info(json):
    df2 = pd.DataFrame(json)
    df2 = df2[['data']]

    #filteredDF2
    #print('결측치 제거 전 전체 크기 : ',len(filteredDF2))
    df2 = df2.dropna(axis=0)
    #filteredDF2
    #print('결측치 제거 후 전체 크기 : ',len(filteredDF2))
    df2dict = df2.to_dict()
    df2dict_dict = list(df2dict.values())
    
    frameinfolist = list(df2dict_dict[0].keys())
    return frameinfolist

In [18]:
def get_frame_data(json):
    df2 = pd.DataFrame(json)
    df2 = df2[['data']]

    #filteredDF2
    #print('결측치 제거 전 전체 크기 : ',len(filteredDF2))
    df2 = df2.dropna(axis=0)
    #filteredDF2
    #print('결측치 제거 후 전체 크기 : ',len(filteredDF2))
    df2dict = df2.to_dict()
    df2dict_dict = list(df2dict.values())
    
    
    framedatalist = list(df2dict_dict[0].values())
    return framedatalist

#### 3-3) 테스트
- 크기가 커서 튕길 수 있는 관계로 부득이 주석처리를 해두겠습니다.

In [19]:
tmplist = get_frame_info(clip_13)
tmpseries1 = pd.Series(tmplist)
tmpseries1

0       1143
1        241
2       1535
3        566
4        395
        ...
1570     138
1571     486
1572     637
1573     452
1574    1167
Length: 1575, dtype: object

In [20]:
tmplist = get_frame_data(clip_13)
tmpseries2= pd.Series(tmplist)
tmpseries2

0       {'2': {'frame': '1143', 'predicate': {'2': 'si...
1       {'2': {'frame': '241', 'predicate': {'2': 'sit...
2       {'2': {'frame': '1535', 'predicate': {'2': 'si...
3       {'2': {'frame': '566', 'predicate': {'2': 'sit...
4       {'2': {'frame': '395', 'predicate': {'2': 'sit...
                              ...
1570    {'2': {'frame': '138', 'predicate': {'2': 'sit...
1571    {'2': {'frame': '486', 'predicate': {'2': 'sit...
1572    {'2': {'frame': '637', 'predicate': {'2': 'sit...
1573    {'2': {'frame': '452', 'predicate': {'2': 'sit...
1574    {'2': {'frame': '1167', 'predicate': {'2': 'si...
Length: 1575, dtype: object

### 4. clip13DF2['data']에 상당히 깊은 깊이가 존재합니다. 이를 해결하기 위해 분화를 해줍니다.

In [21]:
framedatalist  = get_frame_data(clip_13)

- framedatalist는 frame 별로 dictionary 자료형을 담고 있는 객체입니다.

In [22]:
framedataDF0 = pd.DataFrame(framedatalist[0])
framedataDF0= framedataDF0.transpose()
framedataDF0

,frame,predicate,emotion,xtl,label,ybr,position,ytl,text,xbr,person_id
2,1143,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",481.90,사람,1059.60,{'1': 'ahead_behind'},129.80,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",912.70,2
3,1143,{},NaN,963.84,물잔,464.75,{},398.48,NaN,1031.61,NaN
1,1143,{'1': 'eat_drink'},"{'image': {'valence': 8.0, 'emotion': 'happy',...",815.93,사람,965.10,{'2': 'ahead_behind'},130.04,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",1368.53,2
4,1143,{},NaN,847.90,물잔,475.25,{},398.50,NaN,912.55,NaN

In [23]:
framedataDF1 = pd.DataFrame(framedatalist[1])
framedataDF1 = framedataDF1.transpose()
framedataDF1

,frame,predicate,label,xtl,position,ytl,ybr,xbr,person_id
2,241,"{'2': 'sit', '4': 'eat_drink'}",사람,464.95,{'1': 'ahead_behind'},106.31,1002.40,923.56,2
3,241,{},물잔,963.84,{},398.48,464.75,1031.61,NaN
1,241,{'1': 'catch'},사람,831.86,{'2': 'ahead_behind'},131.18,962.81,1389.24,2
4,241,{},물잔,708.09,{},224.21,312.10,793.12,NaN

In [24]:
#figuredataDF1 = pd.DataFrame(data = list(figuredata[0].values()),columns = list(figuredata[0].keys()))
# figuredataDF1= pd.DataFrame(data = tmp2,columns=tmp1)
# figuredataDF1

#### 4-1) get_data column_list : 중요!! 원본 데이터프레임에서 깊이가 깊은 data 컬럼의 수많은 네스티드 구조를 전부 컬럼으로 만들고, 하나의 데이터프레임을 반환하는 함수

- 그러니까, 처음부터 이야기 하자면, 전체 json 파일에서 긁어낸 데이터프레임 중, data 컬럼만 띡 뽑아내고
- 모든 frame(1143,241,1167...)별로 싹 전부 메타 정보를 한눈에 볼 수 있게 정리해주는 함수입니다.

In [25]:
def get_data_column_list(json):
    framedatalist = get_frame_data(json)
    ## 맨 처음 0번째 1143 frame의 데이터프레임
    framedataDF0 = pd.DataFrame(framedatalist[0])
    framedataDF0= framedataDF0.transpose()
    
    Total_Count_Of_Frame = len(framedatalist)
    
    for i in range(1,Total_Count_Of_Frame):
        framedatanext = pd.DataFrame(framedatalist[i])
        framedatanext = framedatanext.transpose()
        framedataDF0 = framedataDF0.append(framedatanext)
    
    return framedataDF0

#### 4-1-1) 테스트

In [26]:
tmpDataFrame = get_data_column_list(clip_13)
tmpDataFrame.columns

Index(['frame', 'predicate', 'emotion', 'xtl', 'label', 'ybr', 'position',
       'ytl', 'text', 'xbr', 'person_id'],
      dtype='object')

In [44]:
tmpDataFrame

,frame,predicate,emotion,xtl,label,ybr,position,ytl,text,xbr,person_id
2,1143,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",481.90,사람,1059.60,{'1': 'ahead_behind'},129.80,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",912.70,2
3,1143,{},NaN,963.84,물잔,464.75,{},398.48,NaN,1031.61,NaN
1,1143,{'1': 'eat_drink'},"{'image': {'valence': 8.0, 'emotion': 'happy',...",815.93,사람,965.10,{'2': 'ahead_behind'},130.04,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",1368.53,2
4,1143,{},NaN,847.90,물잔,475.25,{},398.50,NaN,912.55,NaN
2,241,"{'2': 'sit', '4': 'eat_drink'}",NaN,464.95,사람,1002.40,{'1': 'ahead_behind'},106.31,NaN,923.56,2
...,...,...,...,...,...,...,...,...,...,...,...
4,452,{},NaN,847.90,물잔,475.25,{},398.50,NaN,912.55,NaN
2,1167,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",481.90,사람,1059.60,{'1': 'ahead_behind'},127.61,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",912.70,2
3,1167,{},NaN,963.84,물잔,464.75,{},398.48,NaN,1031.61,NaN
1,1167,{'1': 'eat_drink'},"{'image': {'valence': 8.0, 'emotion': 'happy',...",816.75,사람,965.10,{'2': 'ahead_behind'},129.86,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",1369.35,2
4,1167,{},NaN,847.90,물잔,475.25,{},398.50,NaN,912.55,NaN

### 5. 이제 또 다시 분화를 해야합니다.
- 5-1)
- emotion에 또다시 image, multimodal,sound, text로 나뉘고
  - image 안에는 valence, emotion, arousal이 있고
  - sound 안에도 valence, emotion, arousal이 있고
  - text 안에도 valence, emotion,arousal이 있고 있습니다.
- text에는 또다시 strategy, script_start,script_end,script,intent,morpheme으로 나뉩니다. 
  - strategy : 문자열
  - script_start,script_end : int
  - script : 문자열
  - intent : 문자열
  - morpheme : 2차원 배열입니다. 
     - 모든 2차원 배열의 요소는 총 2개의 원소가 들어있습니다.
         - 형태소 : 문장성분입니다. 예를 들어 "알","VV" 이런 식인데
         - 알은 술부 / VV가 Verb?를 나타내는 것 같습니다. 
         


- 5-2)
- 필요해 보이는 함수에는 어떠한게 있을까요?
  - frame 번호를 입력하면, 그에 해당하는 emotion의 정보를 담은 DataFrame을 반환하는 함수
  - frame 번호를 입력하면, 그에 해당하는 script를 반환하는 함수
  - ** 추가로 필요한 함수가 있다면 말씀해주세요. 최대한 만들어보겠습니다....................................

In [27]:
TotalDataFrame = get_data_column_list(clip_13)

#### 5-1) get_emotion : frame 별로 사람에 대한 감정 정보만을 담은 dataFrame을 추출하는 함수

- 이 함수가 필요한 이유는 어차피 사람의 감정을 초점으로 맞췄고, 사람만이 대사를 칠 수 있기 때문에 필요하지 않은 물건(물병, 텀블러)들을 담은 정보를 제거하는게 preprocessing에 도움이 되기 때문입니다.

- 따라서, label 컬럼도 삭제됩니다. 왜냐하면 명시하지 않아도 사람임이 확실하기 때문입니다.

In [28]:
def get_emotion(json):
    TotalDataFrame = get_data_column_list(json)
    
    PersonEmotionDF = TotalDataFrame.dropna(subset=['emotion'])
    PersonEmotionDF = PersonEmotionDF.drop(['label'],axis=1)
    return PersonEmotionDF

#### 테스트

In [29]:
PersonEmotionDF = get_emotion(clip_13)

PersonEmotionDF

,frame,predicate,emotion,xtl,ybr,position,ytl,text,xbr,person_id
2,1143,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",481.90,1059.60,{'1': 'ahead_behind'},129.80,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",912.70,2
1,1143,{'1': 'eat_drink'},"{'image': {'valence': 8.0, 'emotion': 'happy',...",815.93,965.10,{'2': 'ahead_behind'},130.04,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",1368.53,2
2,566,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",463.84,1002.40,{'1': 'ahead_behind'},119.90,"{'strategy': '자기대화 (SD)', 'script_start': 550,...",929.70,2
1,566,{'1': 'eat_drink'},"{'image': {'valence': 9.0, 'emotion': 'happy',...",819.52,959.06,{'2': 'ahead_behind'},129.24,"{'strategy': '자기대화 (SD)', 'script_start': 550,...",1384.24,2
2,1082,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",474.98,1059.55,{'1': 'ahead_behind'},126.07,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",912.70,2
...,...,...,...,...,...,...,...,...,...,...
1,486,{'1': 'eat_drink'},"{'image': {'valence': 9.0, 'emotion': 'happy',...",823.55,960.15,{'2': 'ahead_behind'},130.33,NaN,1388.27,2
2,452,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",463.84,1002.40,{'1': 'ahead_behind'},112.96,"{'strategy': '자기대화 (SD)', 'script_start': 410,...",936.70,2
1,452,{'1': 'catch'},"{'image': {'valence': 9.0, 'emotion': 'happy',...",824.50,963.77,{'2': 'ahead_behind'},130.76,"{'strategy': '자기대화 (SD)', 'script_start': 410,...",1389.11,2
2,1167,{'2': 'sit'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",481.90,1059.60,{'1': 'ahead_behind'},127.61,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",912.70,2
1,1167,{'1': 'eat_drink'},"{'image': {'valence': 8.0, 'emotion': 'happy',...",816.75,965.10,{'2': 'ahead_behind'},129.86,"{'strategy': '자기대화 (SD)', 'script_start': 980,...",1369.35,2

#### 5-1-1) get_frame_emotion : 특정 프레임의 감정 정보를 담은 데이터프레임을 반환하는 함수

- 검색하고 싶은 frame 정보를 입력하면, 그에 해당하는 DF를 반환하는 함수입니다.
- 앞서 작성하였던 get_frame_info를 통해 frame의 인덱스를 확인하고, 
- 이를 바탕으로 작성해보겠습니다.

In [30]:
target = 1143
#print(type(target))
res=0
tmpdf=pd.DataFrame(columns = PersonEmotionDF.columns)

for i in range(len(PersonEmotionDF['frame'])):
    df=pd.DataFrame()
    if str(target) == PersonEmotionDF['frame'][i]:
         df=pd.DataFrame(PersonEmotionDF.iloc[i,:])
         tmpdf.append(df)

In [31]:
tmpdf

Empty DataFrame
Columns: [frame, predicate, emotion, xtl, ybr, position, ytl, text, xbr, person_id]
Index: []

In [32]:
def get_frame_emotion(target,json):
    target = target
    
    PersonEmotionDF = get_emotion(json)
    resdf = pd.DataFrame()
    
    for i in range(len(PersonEmotionDF['frame'])):
        
        if str(target) == PersonEmotionDF['frame'][i]:
            nextDF = pd.DataFrame(PersonEmotionDF.iloc[i,:])
            nextDF = nextDF.transpose()
            resdf.append(nextDF)
    
    return resdf

In [33]:
tmp = get_frame_emotion(1143,clip_13)
tmp

Empty DataFrame
Columns: []
Index: []

In [34]:
get_data_column_list(clip_30)

,frame,predicate,emotion,label,xtl,position,ytl,ybr,xbr,person_id,text
2,1593,{},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,593.78,{'1': 'ahead_behind'},106.19,957.39,837.77,2,NaN
1,1593,{'null': 'catch'},"{'image': {'valence': 4.0, 'emotion': 'angry',...",사람,1199.91,{'2': 'ahead_behind'},86.31,1031.18,1448.47,2,NaN
2,1143,{},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,609.82,{'1': 'ahead_behind'},106.19,957.39,839.28,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
1,1143,{'3': 'catch'},"{'image': {'valence': 4.0, 'emotion': 'angry',...",사람,1243.30,"{'2': 'ahead_behind', '3': 'reach'}",50.21,1076.39,1583.93,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
3,1143,{},NaN,텀블러,1275.82,{'1': 'reach'},303.17,436.86,1353.52,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1,452,{'3': 'catch'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,952.50,{'2': 'reach'},122.40,966.42,1335.64,2,NaN
3,452,{'3': 'catch'},NaN,텀블러,926.66,"{'2': 'reach', '1': 'reach'}",300.99,411.24,980.22,NaN,NaN
2,1167,{},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,609.29,{'1': 'ahead_behind'},106.19,957.39,838.54,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
1,1167,{'3': 'catch'},"{'image': {'valence': 4.0, 'emotion': 'angry',...",사람,1210.42,"{'2': 'ahead_behind', '3': 'reach'}",75.14,1076.39,1535.14,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
3,1167,{},NaN,텀블러,1220.52,{'1': 'reach'},341.43,457.10,1305.41,NaN,NaN

In [35]:
import pandas as pd
data = {'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
       'Year':[2011,2015,2016,2016],
       'Gender':['Male','Female','Male','Male'],
        }

In [36]:
data_df = pd.DataFrame(data)
data_df

       Name  Year  Gender
0   Chulmin  2011    Male
1  Eunkyung  2015  Female
2  Jinwoong  2016    Male
3   Soobeom  2016    Male

In [37]:
name_data_df = pd.DataFrame(data_df.loc[:,'Name'])

name_data_df

       Name
0   Chulmin
1  Eunkyung
2  Jinwoong
3   Soobeom

In [38]:
print(type(get_data_column_list(clip_30)))

<class 'pandas.core.frame.DataFrame'>

In [39]:
test = get_data_column_list(clip_30)
test

,frame,predicate,emotion,label,xtl,position,ytl,ybr,xbr,person_id,text
2,1593,{},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,593.78,{'1': 'ahead_behind'},106.19,957.39,837.77,2,NaN
1,1593,{'null': 'catch'},"{'image': {'valence': 4.0, 'emotion': 'angry',...",사람,1199.91,{'2': 'ahead_behind'},86.31,1031.18,1448.47,2,NaN
2,1143,{},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,609.82,{'1': 'ahead_behind'},106.19,957.39,839.28,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
1,1143,{'3': 'catch'},"{'image': {'valence': 4.0, 'emotion': 'angry',...",사람,1243.30,"{'2': 'ahead_behind', '3': 'reach'}",50.21,1076.39,1583.93,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
3,1143,{},NaN,텀블러,1275.82,{'1': 'reach'},303.17,436.86,1353.52,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1,452,{'3': 'catch'},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,952.50,{'2': 'reach'},122.40,966.42,1335.64,2,NaN
3,452,{'3': 'catch'},NaN,텀블러,926.66,"{'2': 'reach', '1': 'reach'}",300.99,411.24,980.22,NaN,NaN
2,1167,{},"{'image': {'valence': 5.0, 'emotion': 'neutral...",사람,609.29,{'1': 'ahead_behind'},106.19,957.39,838.54,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
1,1167,{'3': 'catch'},"{'image': {'valence': 4.0, 'emotion': 'angry',...",사람,1210.42,"{'2': 'ahead_behind', '3': 'reach'}",75.14,1076.39,1535.14,2,"{'strategy': '질문대화 (QESD)', 'script_start': 11..."
3,1167,{},NaN,텀블러,1220.52,{'1': 'reach'},341.43,457.10,1305.41,NaN,NaN

In [40]:
emotion_ = test['emotion']
emotion_

2    {'image': {'valence': 5.0, 'emotion': 'neutral...
1    {'image': {'valence': 4.0, 'emotion': 'angry',...
2    {'image': {'valence': 5.0, 'emotion': 'neutral...
1    {'image': {'valence': 4.0, 'emotion': 'angry',...
3                                                  NaN
                           ...
1    {'image': {'valence': 5.0, 'emotion': 'neutral...
3                                                  NaN
2    {'image': {'valence': 5.0, 'emotion': 'neutral...
1    {'image': {'valence': 4.0, 'emotion': 'angry',...
3                                                  NaN
Name: emotion, Length: 5499, dtype: object

In [41]:
emotion_.values[0]

{'image': {'valence': 5.0, 'emotion': 'neutral', 'arousal': 5.0}}

In [42]:
emotion_.values[0].keys()

dict_keys(['image'])

In [43]:
emotion_.values[0].values()

dict_values([{'valence': 5.0, 'emotion': 'neutral', 'arousal': 5.0}])