### Pandas 시작 - 파일을 DataFrame 로딩, 기본 API

In [1]:
import pandas as pd

In [2]:
titanic_df = pd.read_csv('C:/Users/user/Jupyter_project/PerfectGuide-master/1장/titanic/train.csv')
print('titanic 변수 type :',type(titanic_df))

titanic 변수 type : <class 'pandas.core.frame.DataFrame'>

#### head()
DataFrame의 맨 앞 일부 데이터만 추출합니다.

In [3]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### DataFrame의 생성

In [4]:
dic1 = {'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
       'Year':[2011,2015,2015,2015],
       'Gender':['Male','Female','Male','Male']
       }

#딕셔너리를 DataFrame으로 변환
data_df = pd.DataFrame(dic1)

print(data_df)
print('#'*30)

# 새로운 컬럼 명을 추가
data_df = pd.DataFrame(dic1,columns = ["Name","Year","Gender","Age"])
print(data_df)
print('#'*30)
#인덱스를 새로운 값으로 할당
data_df = pd.DataFrame(dic1,index = ['one','two','three','four'])

print(data_df)
print('#'*30)

       Name  Year  Gender
0   Chulmin  2011    Male
1  Eunkyung  2015  Female
2  Jinwoong  2015    Male
3   Soobeom  2015    Male
##############################
       Name  Year  Gender  Age
0   Chulmin  2011    Male  NaN
1  Eunkyung  2015  Female  NaN
2  Jinwoong  2015    Male  NaN
3   Soobeom  2015    Male  NaN
##############################
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2015  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male
##############################

#### DataFrame의 컬럼명과 인덱스 출력

In [5]:
print("columns :",titanic_df.columns)
print("index :",titanic_df.index)
print("index value :",titanic_df.index.values)

columns : Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
index : RangeIndex(start=0, stop=891, step=1)
index value : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

#### DataFrame에서 Series를 추출하고 DataFrame 필터링하는 방법

In [6]:
# DataFrame 객체에서 []연산자 내에 한개의 컬럼만 입력하면, Series 객체를 반환합니다.

series = titanic_df['Name']
print(series.head())
print(type(series))


#DataFrame 객체에서 []연산자 내에 여러개의 컬럼을 리스트로 입력하면 
#그 컬럼들로 구성된 DataFrame을 반환합니다.

filtered_df = titanic_df[['Name','Age']]

print(filtered_df.head(3))

print("## type:",type(filtered_df))

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object
<class 'pandas.core.series.Series'>
                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
## type: <class 'pandas.core.frame.DataFrame'>

#### shape는 DataFrame의 행과 열 크기를 가지고 있는 메서드입니다.

In [7]:
print(titanic_df.shape)

(891, 12)

#### info()는 DataFrame 내 컬럼명, 데이터 타입, Null건수, 데이터 건수 정보를 제공

In [8]:
print(titanic_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

#### describe() : 데이터값들의 평균, 표준편차, 4분위 분포도를 제공합니다.
#### 숫자형 컬럼들에 대해 해당 정보를 제공합니다.
#### 왜냐하면 int / float와 같은 숫자형 데이터들에 한해서 연산이 가능하기 때문입니다.

In [9]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#### value_counts()
- 동일한 개별 데이터 값이 총 몇 건이 존재하는지에 대한 정보를 제공합니다. 
- 즉 개별 데이터값의 분포도를 제공합니다.
- 주의할 점은 vlues_counts()는 Series 객체에서만!!! 호출될 수 있다는 점
- 따라서 DataFrame을 1차원의 단일 컬럼으로 입력하여, Series로 변환한 다음 호출

In [10]:
value_counts = titanic_df['Pclass'].value_counts()

print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [11]:
titanic_pclass = titanic_df['Pclass']
#하나의 단일한 Series객체가 되는 것입니다.
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [12]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

#### sort_values()
- by= 정렬 기준 컬럼, ascending=True / False로 오름차순 내림차순 정렬

In [13]:
titanic_df.sort_values(by='Pclass',ascending=True)
#전체 titanic_df에 대해 Pclass를 기준으로 정렬

titanic_df[['Name','Age']].sort_values(by='Age')
#Name,Age만을 뽑아낸 전체 배열에서 Age를 기준으로 정렬

titanic_df[['Name','Age','Pclass']].sort_values(by=['Pclass','Age'])
#Name, Age,Pclass만을 뽑아낸 DataFrame에서 Pclass와 Age를 기준으로 정렬

                                         Name    Age  Pclass
305            Allison, Master. Hudson Trevor   0.92       1
297              Allison, Miss. Helen Loraine   2.00       1
445                 Dodge, Master. Washington   4.00       1
802       Carter, Master. William Thornton II  11.00       1
435                 Carter, Miss. Lucile Polk  14.00       1
..                                        ...    ...     ...
859                          Razi, Mr. Raihed    NaN       3
863         Sage, Miss. Dorothy Edith "Dolly"    NaN       3
868               van Melkebeke, Mr. Philemon    NaN       3
878                        Laleff, Mr. Kristo    NaN       3
888  Johnston, Miss. Catherine Helen "Carrie"    NaN       3

[891 rows x 3 columns]

In [14]:
NAP_titanic_df = pd.DataFrame(data = titanic_df[['Name','Age','Pclass']])
NAP_titanic_df

                                                  Name   Age  Pclass
0                              Braund, Mr. Owen Harris  22.0       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1
2                               Heikkinen, Miss. Laina  26.0       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1
4                             Allen, Mr. William Henry  35.0       3
..                                                 ...   ...     ...
886                              Montvila, Rev. Juozas  27.0       2
887                       Graham, Miss. Margaret Edith  19.0       1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN       3
889                              Behr, Mr. Karl Howell  26.0       1
890                                Dooley, Mr. Patrick  32.0       3

[891 rows x 3 columns]

### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

#### 1) 리스트 ,ndarray에서 DataFrame으로 변환

In [15]:
import numpy as np

col_name1=['col1']
list1 = [1,2,3]

array1 = np.array(list1)
#리스트 객체를 ndarray로 변환한 결과

print('array1 shape:',array1.shape)

df_list1 = pd.DataFrame(list1, columns = col_name1)
#데이터프레임으로의 변환을 list로 하였음

print('1차원 리스트로 만든 DataFrame: \n', df_list1)

df_array1 = pd.DataFrame(array1,columns = col_name1)
print('1차원 ndarray로 만든 DataFrame: \n',df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

정리 : ndarray, list 객체 모두 data = ndarray, data = list를 통해 DataFrame으로 만들 수 있다.

In [16]:
#3개의 경우 어떻게 될까?

col_name2 = ['col1','col2','col3']

#2행 3열 형태의 리스트와 ndarray를 생성한 뒤, 이를 DataFrame으로 변환하겠습니다.
list2=[]
for i in range(2):
    tmp=[]
    if i == 0:
        for j in range(1,4):
            tmp.append(j)
        
    elif i==1:
        for j in range(1,4):
            tmp.append(i*10+j)
        
    list2.append(tmp)
        
list2

array2 = np.array(list2)
array2
print('array2 shape:',array2.shape)

df_list2 = pd.DataFrame(data = list2, columns = col_name2)
print('2차원 리스트로 만든 데이터 프레임:',df_list2)

df_array2 = pd.DataFrame(data = array2,columns=col_name2)
print('2차원 ndarray로 만든 데이터 프레임:',df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 데이터 프레임:    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 데이터 프레임:    col1  col2  col3
0     1     2     3
1    11    12    13

### 딕셔너리에서 DataFrame으로 변환 오 이거 되게 중요하다.

In [17]:
#key 값은 컬럼명으로 매핑, Value는 리스트 형(혹은 ndarray로)

dict1 = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}

dict_df = pd.DataFrame(dict1)
print(dict_df)

print('딕셔너리로 만든 DataFrame : \n',dict_df)

   col1  col2  col3
0     1     2     3
1    11    22    33
딕셔너리로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    22    33

### DataFrame을 이제 다시 ndarray로 변환!!

- 지금까지의 작업을 정반대로 진행합니다.

In [18]:
#DataFrame을 리스트로 변환
list3 = dict_df.values.tolist()

print('dict_df.values.tolist()를 한 결과의 데이터 타입 :',type(list3))
print(list3)

#DataFrame을 다시 딕셔너리로 변환
dict3 = dict_df.to_dict('list')
print('\n df_dict.to_dict(데이터 타입) :',type(dict3))
print(dict3)

dict_df.values.tolist()를 한 결과의 데이터 타입 : <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict(데이터 타입) : <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

#### DataFrame의 컬럼 데이터셋 Access

- DataFrame의 컬럼 데이터셋 생성 / 수정은 [] 연산자를 이용해 쉽게 할 수 있다.
- 새로운 컬럼에 값을 할당하려면, DataFrame[새로운 컬럼명] = 값 이렇게 할당을 해주면 된다.

In [19]:
titanic_df['Age_0']=0
titanic_df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [20]:
titanic_df['Age_by_10']=titanic_df['Age']*10
#이런식으로 곱한 결과를 1대1 매칭하기도 한다.
titanic_df['Family_No'] = titanic_df['SibSp']+titanic_df['Parch']+1

titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

#### 기존 컬럼에 대한 값을 일괄적으로 변경하려면 그냥 연산을 하면 된다.

In [21]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10']+100

titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

#### DataFrame 데이터를 삭제 하는 방법

- axis에 따른 삭제

In [22]:
titanic_drop_df = titanic_df.drop(['Age_0'],axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [23]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

#### 여러 컬럼들의 삭제는 drop의 인자로 삭제할 컬럼들을 리스트로 입력한다.

- inplace = True일 경우 호출을 한 DataFrame에 drop이 반영된다. 이때, 반환값은 None이다.

In [24]:
drop_result1 = titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=False)

print('inplace = False로 했을 때 반환된 값 : ',drop_result1)

print()
titanic_df.head(3)

inplace = False로 했을 때 반환된 값 :       PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

### 오 이거 꿀팁. 만일 axis가 0으로 설정된 경우, drop()은 row 방향으로 데이터를 삭제합니다.

In [25]:
titanic_df = pd.read_csv('C:/Users/user/Jupyter_project/PerfectGuide-master/1장/titanic/train.csv')

pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)

print('#### before axis 0 drop ####')

print(titanic_df.head(5))

titanic_df.drop([0,1,2],axis=0,inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

#### Index 객체에 대하여

In [26]:
#원본 파일을 재로딩합니다.
titanic_df = pd.read_csv('C:/Users/user/Jupyter_project/PerfectGuide-master/1장/titanic/train.csv')

#index 객체를 추출합니다.

indexes = titanic_df.index
print(indexes)

RangeIndex(start=0, stop=891, step=1)

#### 이 indexes 객체는 배열이 아니다. 이것을 한번 더 배열로 반환을 해줘야 한다. 
- case 1 : index.values로 iteration을 가능하게 한다.
- case 2 : 리스트 객체 하나를 만들고 index.values를 할당한다.

In [27]:
#ndarray로의 변환
tmparray = np.array(indexes)
print(tmparray)
print('변환된 ndarray의 타입 :',type(tmplist))

#list로의 변환
tmplist = []
tmplist = indexes.values

print(tmplist)
print('변환된 list의 타입 :',type(tmplist))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

NameError: name 'tmplist' is not defined

이 index는 1차원 배열처럼 사용할 수 있다.

In [ ]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])

#### Series 객체는 index객체를 포함하지만, 직접적으로 어떤 연산을 위한 함수를 적용할 때 index는 연산에서 제외됩니다.

- index는 오로지 PK, 즉 식별자로만 쓰입니다.

In [ ]:
series_fair = titanic_df['Fare']

series_fair.head(5)

In [ ]:
print('Fair Series Max : ',series_fair.max())
print('Fair Series sum :',series_fair.sum())
print('sum() Fair Series :',sum(series_fair))
print('Fair_series +3 : \n',(series_fair+3).head(3))

#### reset_index() : 인덱스를 연속 숫자형으로 할당하고, 쉽게 말해 index와 똑같은 것을 하나 추가한다.

In [ ]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(5)
titanic_reset_df['Survived']

In [ ]:
print('### before reset index ###')
value_counts = titanic_df['Pclass'].value_counts()

#Series 객체로 만들어야 value_counts로 만들 수 있다.

print('value_counts 객체 변수 타입 :',type(value_counts))

new_value_counts = value_counts.reset_index(inplace=False)

print('### After reset_index ###')

print(new_value_counts)

print('new_value_counts 객체 변수 타입 : ',type(new_value_counts))